update buildco2 check-inner to use ssh wrapper

diff --git a/buildco2/check-inner b/buildco2/check-inner
--- a/buildco2/check-inner
+++ b/buildco2/check-inner
@@ -84,10 +84,15 @@ if [ $needbuild -ne 0 ] ; then
         echo
     else
         git commit -m "automatically update to inner project hash $(cat hashtobuild)"
-        git push -q https://$GITHUB_PROJECT_TOKEN@github.com/$GITHUB_USER/$GITHUB_REPO
-        sleep 3
-        git push -q https://$GITHUB_PROJECT_TOKEN@github.com/$GITHUB_USER/$GITHUB_REPO
-        echo
+        if [ -f ../ssh_wrapper.sh ]; then 
+            GIT_SSH='../ssh_wrapper.sh' git push -q https://github.com/$GITHUB_USER/$GITHUB_REPO
+            sleep 3
+            GIT_SSH='../ssh_wrapper.sh' git push -q https://github.com/$GITHUB_USER/$GITHUB_REPO
+            echo
+        else
+            echo "Failed to find ssh_wrapper."
+            exit 1
+        fi
     fi
 fi
 
